# Generated by Django 2.2.6 on 2019-11-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0002_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='step',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
